[package]
name = "ffcli"
version = "0.1.0"
authors = ["Donough Liu <ldm2993593805@163.com>"]
edition = "2018"

[dependencies]
libc = "0.2.71"
bitflags = "1.2.1"
once_cell = "1.4.0"
log = "0.4.8"
env_logger = "0.7.1"
memoffset = "0.5.4"
rusty_ffmpeg = "0.1.0"
